# Example configuration file for Fiber Tracer
# Copy this file and modify according to your needs

# Required paths
data_dir: "/path/to/your/tiff/images"
output_dir: "/path/to/output/directory"

# Optional: limit number of images to process
# num_images: 500

# Image sorting order
sort_order: "Name (Ascending)"

# Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_level: "INFO"

# Processing configuration
processing:
  chunk_size: 100        # Number of images per chunk
  scale_factor: 1        # Downscaling factor (1 = no downscaling)
  num_workers: null      # Number of parallel workers (null = auto-detect)
  median_disk_size: 2    # Size of median filter disk
  gaussian_sigma: 1.0    # Gaussian filter sigma
  clahe_clip_limit: 0.03 # CLAHE clip limit for contrast enhancement

# Segmentation configuration
segmentation:
  block_size: 51         # Block size for adaptive thresholding
  min_object_size: 500   # Minimum object size in pixels
  adaptive_threshold: true
  fill_holes: true

# Fiber analysis configuration
analysis:
  min_diameter: 10.0     # Minimum fiber diameter (micrometers)
  max_diameter: 50.0     # Maximum fiber diameter (micrometers)
  voxel_size: 1.1        # Voxel size (micrometers)
  angle_bins: [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180]
  calculate_tortuosity: true
  calculate_orientation: true

# Visualization configuration
visualization:
  generate_heatmap: true
  generate_histogram: true
  generate_3d_visualization: true
  use_mayavi: false      # Mayavi is difficult to install
  use_plotly: true       # Use Plotly for interactive 3D plots
  colormap: "viridis"
  figure_dpi: 150
  save_format: "png"
