# Conda environment file for Fiber Tracer
# Create environment with: conda env create -f environment.yml
# Activate with: conda activate fiber_tracer

name: fiber_tracer
channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  # Python version
  - python=3.9
  
  # Core scientific packages
  - numpy>=1.21.0,<2.0.0
  - scipy>=1.7.0
  - scikit-image>=0.19.0
  - opencv>=4.5.0
  
  # Data analysis
  - pandas>=1.3.0
  - openpyxl>=3.0.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.3.0
  
  # Utilities
  - tqdm>=4.62.0
  - pyyaml>=5.4.0
  
  # Optional: Advanced 3D visualization
  # Uncomment if needed (may require additional setup)
  # - mayavi>=4.7.0
  # - vtk>=9.0.0
  
  # Development tools (optional)
  - ipython
  - jupyter
  - notebook
  
  # Pip dependencies not available in conda
  - pip
  - pip:
    # Add any pip-only packages here if needed
    # - some-package==1.0.0
